
const nav=document.getElementById('nav'),bar=document.getElementById('bar'),menu=document.getElementById('menu'),links=document.getElementById('links');
addEventListener('scroll',()=>{if(nav)nav.classList.toggle('scrolled',scrollY>20);if(bar){let h=document.documentElement.scrollHeight-innerHeight;bar.style.width=(h?scrollY/h*100:0)+'%'}});
if(menu)menu.onclick=()=>links.classList.toggle('mobile');
document.querySelectorAll('.links a').forEach(a=>a.onclick=()=>links.classList.remove('mobile'));
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('show')}),{threshold:.1});
document.querySelectorAll('.reveal').forEach(e=>io.observe(e));
document.querySelectorAll('form[data-demo]').forEach(f=>f.onsubmit=e=>{e.preventDefault();alert('Demo form submitted. Connect your real email/WhatsApp/backend before launch.');});
(function(){const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;const splash=document.querySelector('.splash');if(splash){if(reduce)splash.classList.add('hide');else setTimeout(()=>splash.classList.add('hide'),850)}document.querySelectorAll('a[href$=".html"]').forEach(a=>a.addEventListener('click',e=>{const u=a.getAttribute('href');if(!u||a.target==='_blank')return;e.preventDefault();const o=document.querySelector('.page-transition');if(o)o.classList.add('on');setTimeout(()=>location.href=u,180)}));const theme=document.querySelector('[data-theme-toggle]');if(localStorage.getItem('kb-theme')==='light')document.body.classList.add('light');if(theme)theme.onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('kb-theme',document.body.classList.contains('light')?'light':'dark');theme.textContent=document.body.classList.contains('light')?'☀':'☾'};const chips=document.querySelectorAll('.service-chip'),result=document.querySelector('.service-result');const copy={website:['Website Development','Responsive business websites, landing pages and portfolios built around your goals.'],ecommerce:['E-Commerce','Product catalogs, carts, checkout flows and payment-ready storefronts.'],app:['Web Applications','Custom dashboards, portals, booking systems and business workflows.'],design:['UI/UX Design','Clear interfaces, visual systems and customer journeys designed for action.']};chips.forEach(c=>c.onclick=()=>{chips.forEach(x=>x.classList.remove('active'));c.classList.add('active');const d=copy[c.dataset.service];if(result&&d)result.innerHTML='<div class="card"><div class="kicker">SELECTED SERVICE</div><h3>'+d[0]+'</h3><p class="muted">'+d[1]+'</p></div>'})})();
